### ISSUE TITLE
Call to undefined method  PhalconRestJWT\Bootstrap\ServiceBootstrap::get()

### ISSUE THREAD

**Issue by titandevph** [nerfe/phalconphp-rest-jwt-acl#1]
Hi,

I'm getting an error when getting data from db. Looks like in the setEventsManager.

PHP message: PHP Fatal error:  Call to undefined method PhalconRestJWT\Bootstrap\ServiceBootstrap::get() in /opt/rest-api/app/library/bootstrap/ServiceBootstrap.php on line 44

**Comment by wassapaks** [comment]
Hello what phalcon version are you using?

**Comment by titandevph** [comment]
![image](https://cloud.githubusercontent.com/assets/8244663/19759007/805cdb10-9c5d-11e6-9b7b-fb7a710cfe24.png)

**Comment by wassapaks** [comment]
I have pushed some updates, instead of using $this i used the $di instead, i think its a problem for php 5.6. you can see it in 

library/bootstrap/ServiceBootstrap.php 

thanks for reporting

**Comment by titandevph** [comment]
Great, that fix the issue.
