### ISSUE TITLE
can't create acl.data

### ISSUE THREAD

**Issue by xeleniumz** [nerfe/phalconphp-rest-jwt-acl#2]
hello nerfe . I got the problem when use acl. here is an error. I try to check AclRoles but i didn't know why it didn't create acl file in cache folder.
`<br/>
<b>Notice</b>: unserialize(): Error at offset 0 of 1 bytes in
<b>/var/www/html/api/public_html/v2/app/library/security/AclRoles.php</b> on line
<b>89</b>
<br/>
<br/>
<b>Fatal error</b>: Uncaught Error: Call to a member function isAllowed() on boolean in /var/www/html/api/public_html/v2/app/library/security/AclRoles.php:91
Stack trace:
#0 /var/www/html/api/public_html/v2/app/library/events/Acl.php(44): PhalconRestJWT\Security\AclRoles::getAcl('4C085AF7-C337-4...', 'ExampleControll...', 'testAuth')
#1 [internal function]: PhalconRestJWT\Events\Acl-&gt;beforeExecuteRoute(Object(Phalcon\Events\Event), Object(PhalconRestJWT\App\Micro), NULL)
#2 [internal function]: Phalcon\Events\Manager-&gt;fireQueue(Object(SplPriorityQueue), Object(Phalcon\Events\Event))
#3 [internal function]: Phalcon\Events\Manager-&gt;fire('micro:beforeExe...', Object(PhalconRestJWT\App\Micro))
#4 /var/www/html/api/public_html/v2/app/library/app/Micro.php(176): Phalcon\Mvc\Micro-&gt;handle()
#5 /var/www/html/api/public_html/v2/public/index.php(119): PhalconRestJWT\App\Micro-&gt;run()
#6 {main}
thrown in
<b>/var/www/html/api/public_html/v2/app/library/security/AclRoles.php</b> on line
<b>91</b>
<br/>`

**Comment by wassapaks** [comment]
Sorry i was out on holidays will check this now.

**Comment by wassapaks** [comment]
When you are hitting the api ```user/initroles``` what error do you get? i just get a fresh pull and its working perfectly. 

please do take not of this

```
NOTE: When adding route and its acl please always run the /user/initroles to generate the ACL list and store it to the cache directory. Will be fixing this process soon.
```

**Comment by xeleniumz** [comment]
sorry for late reply , thanks for your advance now it's work :)

**Comment by wassapaks** [comment]
will soon update a fix for this, so you dont have to run init roles, still making an optimize solution for this process.
