### ISSUE TITLE
404 General: Not Found

### ISSUE THREAD

**Issue by nazakahar** [nerfe/phalconphp-rest-jwt-acl#6]
I am having issues with route not found for everything. I tried to debug but couldn't get pass the $this->handle inside Micro.php because it will call the parent method which is not in PHP in believe. 
I tried the simple routes which does not require authentication at all like:
/example/sampleData 
(for both get and post).

The following is my nginx config:
```
server {
        listen 80;
        #listen [::]:8080;

        root /home/naza/tutorials/temp/phalcon-rest/public;

        # Add index.php to the list if you are using PHP
        index index.html index.php index.htm index.nginx-debian.html;

        server_name phalcon-tut.com www.phalcon-tut.com;

        location / {
                try_files $uri $uri/ /index.php;
        }


        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        }

        location ~* \.(png|gif|jpg|jpeg)$ {
                autoindex on;
        }

}
```
Is there a way for me to troubleshoot what went wrong in the whole setup? The database etc is fine.

**Comment by nazakahar** [comment]
Forget about it.  I just solved it by supplying the Uri inside micro.php like the following:
```
$this->handle($_SERVER['REQUEST_URI']);
```

**Comment by wassapaks** [comment]
Can you share with me your Phalconphp version and your PHP version? if you are using the latest versions i guess your nginx config ```location /``` should be like this

``` 
location / {
	        if (-f $request_filename) {
        	    break;
	        }
		# otherwise rewrite it
	        if (!-e $request_filename) {
	            rewrite ^(.+)$ /index.php?_url=$1 last;
        	    break;
	        }

}
```

You can omit the first if condition if you want. sorry for the late reply.
